### ISSUE TITLE
Application doesn't open after it is closed until pressing "quit" from the system tray

### ISSUE THREAD

**Issue by rowak** [StijnOostdam/Winleafs#52] opened 2019-02-27 15:39 UTC
Closing the application by pressing the "x" in the top-right corner or killing from task manager causes the window to not appear the next time the app is run.

**Comment by StijnOostdam** [comment] 2019-04-03 20:04
Cannot reproduce. This is partly intended behaviour: closing Winleafs via the top right corner causes it to minimize. An option will be added in #75.

**Closed by StijnOostdam** 2019-04-03 20:04 UTC
Labels: bug

**Comment by rowak** [comment] 2019-04-03 23:45
Here's a video showing what this issue looks like: https://streamable.com/6vmn5.

Notice how when I open the app for the first time the UI appears, but it doesn't appear when I close it and reopen it.

**Comment by StijnOostdam** [comment] 2019-04-04 07:32
Thank you for the video. This is intended behaviour. Firstly, when you press close on the main window, the app is not really closed but minimized to your system tray. Secondly, we capture that there only may be one active instance of Winleafs at all times and when you open the app via the shortcut, it tries to start for a second time but that is blocked. We could try and look into opening the main window of you try to open a second instance, see #76.
